### PR TITLE
Restructure Extensions

### PR DESCRIPTION
**Pull request by 3lvis**
Added a DNA folder following Finnivers.

folders

### CODE REVIEW

**Comment by ingridvf** [comment]
In Finnivers I have differentiated between "Elements" and  "components", but it is hard to know the difference. Troika web also calls everything components. Should I remove "Elements"-title in Finnivers and just move everything under "Components"?

**Comment by 3lvis** [comment]
@ingridvf I think that would be a good idea. Hard to see what is an element.

**Comment by ingridvf** [comment]
@3lvis done:)

**Comment by ag12** [comment]
screen shot 2017-12-19 at 14 19 38

Can we now remove the Project.xcodeproj?

**Comment by ag12** [comment]
screen shot 2017-12-19 at 14 19 30

Also, IMO i think its SUPER nice to have the same structure in each folder.
Example: `Playground` folder/group is the first folder you see after expanding root folder.

**Comment by 3lvis** [comment]
@ag12 >Can we now remove the Project.xcodeproj?

That's just in your local copy, if you see the files on GitHub Project.xcodeproj is not there. Make sure to delete it locally.

https://github.com/finn-no/troika-ios

**Comment by 3lvis** [comment]
@ag12 Playground is at the top for all the components now.


screen shot 2017-12-19 at 14 39 30

**Pull request merged**
